# Generated by Django 4.1.3 on 2022-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
