# Generated by Django 4.1.3 on 2022-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_link',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
